name: SwapSpot
description: "A C2C barter marketplace for Kenya"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.16.1
  firebase_storage: ^11.7.0
  firebase_messaging: ^14.7.10
  cloud_functions: ^4.5.8
  flutter_local_notifications: ^16.3.3

  # State Management
  provider: ^6.1.1

  # UI & Navigation
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  video_player: ^2.8.1
  flutter_image_compress: ^2.2.0

  # Utilities
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.1.0
  uuid: ^4.2.1
  intl: ^0.19.0
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  flutter_chips_input: ^1.9.5

  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700