// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Mvpky7QT7MF7Q5dsX9fo3MaQ0L2ERCQ',
    appId: '1:692402083154:web:6425d24feff3d5ce07d68b',
    messagingSenderId: '692402083154',
    projectId: 'swapspot-5a89c',
    authDomain: 'swapspot-5a89c.firebaseapp.com',
    storageBucket: 'swapspot-5a89c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrZv00X_pMcT8imPUWwf83hLVVH2DImy8',
    appId: '1:692402083154:android:d9067f0bbda6f99307d68b',
    messagingSenderId: '692402083154',
    projectId: 'swapspot-5a89c',
    storageBucket: 'swapspot-5a89c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGBZ4cGZMb_r3Cq68ebm5n96yBZGMdf0k',
    appId: '1:692402083154:ios:3091ee657fe2acc107d68b',
    messagingSenderId: '692402083154',
    projectId: 'swapspot-5a89c',
    storageBucket: 'swapspot-5a89c.firebasestorage.app',
    iosBundleId: 'com.example.swapspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGBZ4cGZMb_r3Cq68ebm5n96yBZGMdf0k',
    appId: '1:692402083154:ios:3091ee657fe2acc107d68b',
    messagingSenderId: '692402083154',
    projectId: 'swapspot-5a89c',
    storageBucket: 'swapspot-5a89c.firebasestorage.app',
    iosBundleId: 'com.example.swapspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Mvpky7QT7MF7Q5dsX9fo3MaQ0L2ERCQ',
    appId: '1:692402083154:web:276859dd6753417f07d68b',
    messagingSenderId: '692402083154',
    projectId: 'swapspot-5a89c',
    authDomain: 'swapspot-5a89c.firebaseapp.com',
    storageBucket: 'swapspot-5a89c.firebasestorage.app',
  );
}
